export default {
    USER_LOGIN: "USER_LOGIN",
    GET_ERROR: "GET_ERROR",
    REQUEST_POSTS: "REQUEST_POSTS",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_FILTERS: "GET_FILTERS",
    GET_PRODUCT_SEARCH: "GET_PRODUCT_SEARCH",
    ADD_TO_CART: "ADD_TO_CART",
    FILTER_BY_COLOR: "FILTER_BY_COLOR",
    FILTER_BY_BRAND: "FILTER_BY_BRAND",
    FILTER_BY_PRICE: "FILTER_BY_PRICE",
    FILTER_BY_DISCOUNT: "FILTER_BY_DISCOUNT",
    FILTER_RESET: "FILTER_RESET"
}