export default {
    USER_LOGIN: "USER_LOGIN",
    GET_ERROR: "GET_ERROR",
    REQUEST_POSTS: "REQUEST_POSTS",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_FILTERS: "GET_FILTERS",
    GET_PRODUCT_SEARCH: "GET_PRODUCT_SEARCH"
}